#!/usr/bin/ash

run_hook() {
    
    echo getting secret from TPM...
    /usr/bin/tpm2_unseal -c 0x81000000 -p pcr:sha256:0,1,7 > /root_keyfile.bin
    /usr/bin/tpm2_unseal -c 0x81000001 -p pcr:sha256:0,1,7 > /swap_keyfile.bin
    chmod 0400 /root_keyfile.bin
}

# vim: set ft=sh ts=4 sw=4 et:
"$@"
